import Head from 'next/head'
import { useState } from 'react';
import {Flex, Box, Spinner,Center,Text} from '@chakra-ui/react'
import BoxHeader from '../components/BoxHeader';
import Table from '../components/Table';

import { request, gql } from "graphql-request";
import { useQuery } from "react-query";
const endpoint = "https://graphqlzero.almansi.me/api";
const USER_QUERY = gql`
  query{
    users {
      data{
        id
        name
        username
        email
        address{
          street
        }
        phone
        website
      }
    }
      }
`;


const Home=()=>{

    const[showInput,setShowInput]=useState(false)
    const[content,setContent]=useState("")

    const handleSearch=()=>{
         setShowInput(true)
    }

    const handleChange=(e:React.ChangeEvent<HTMLInputElement>)=>{
          setContent(e.target.value)
          console.log(content)
    }
    
    const { data, isLoading, error } = useQuery("users", () => {
        return request(endpoint, USER_QUERY);
      });
      console.log(data)

      if (isLoading) return  <Flex bg="background" minH="100vh" w="100vw" align="center"><Spinner size='xl' color="button" margin="auto"  thickness='4px'/></Flex> 
      if (error) return <Flex bg="background" minH="100vh" w="100vw" align="center"><Text color="red.400">Something went wrong ....</Text></Flex> ;

      
    return(
         <div>
           <Head>
               <title>React task</title>
               <meta name="description" content="Generated by create next app" />
               <link rel="icon" href="/favicon.ico" />
          </Head>
         <main >
            <Flex bg="background" minH="100vh" w="100vw" py={12}>
            <Box bg="white" w="70%" margin="auto"  rounded="md">
                <div>
                    <BoxHeader  showInput={showInput} content={content} handleSearch={handleSearch} handleChange={handleChange}/>
                </div>
                <Table data={data} searchTerm={content}/>
            </Box>
            </Flex>
         </main>
        </div>
    )

}
export default Home